CREATE TABLE "supplier_invoices" (
	"id" text PRIMARY KEY NOT NULL,
	"supplier_name" text NOT NULL,
	"supplier_ico" text,
	"invoice_number" text NOT NULL,
	"invoice_date" date NOT NULL,
	"duzp_date" date,
	"due_date" date,
	"amount_czk" numeric(14, 2) NOT NULL,
	"vat_amount_czk" numeric(14, 2),
	"invoice_currency" text,
	"category" text NOT NULL,
	"rooms" text[],
	"description" text,
	"status" text NOT NULL,
	"source_type" text NOT NULL,
	"drive_file_id" text,
	"drive_file_name" text,
	"drive_url" text,
	"gmail_message_id" text,
	"icloud_file_name" text,
	"auto_processed" boolean,
	"created_at" timestamp with time zone NOT NULL,
	"bank_transaction_id" text,
	"reconciled_at" timestamp with time zone,
	"settlement_transaction_ids" text[],
	"settlement_group_id" text
);
--> statement-breakpoint
CREATE TABLE "revenue_invoices" (
	"id" text PRIMARY KEY NOT NULL,
	"source_type" text NOT NULL,
	"category" text NOT NULL,
	"status" text NOT NULL,
	"invoice_number" text NOT NULL,
	"invoice_date" date NOT NULL,
	"due_date" date,
	"amount_czk" numeric(14, 2) NOT NULL,
	"reservation_number" text,
	"guest_name" text,
	"client_name" text,
	"description" text,
	"bank_transaction_id" text,
	"reconciled_at" timestamp with time zone,
	"settlement_group_id" text,
	"drive_file_id" text,
	"drive_file_name" text,
	"drive_url" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "additional_payments" (
	"id" text PRIMARY KEY NOT NULL,
	"reservation_number" text NOT NULL,
	"description" text NOT NULL,
	"amount_czk" numeric(14, 2) NOT NULL,
	"guest_email" text,
	"guest_name" text,
	"status" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"paid_at" timestamp with time zone,
	"invoice_id" text,
	"stripe_fee_czk" numeric(14, 2),
	"is_main_payment" boolean
);
--> statement-breakpoint
CREATE TABLE "payment_refunds" (
	"id" text PRIMARY KEY NOT NULL,
	"additional_payment_id" text NOT NULL,
	"amount_czk" numeric(14, 2) NOT NULL,
	"refunded_at" timestamp with time zone NOT NULL,
	"reason" text,
	"refunded_by" text,
	"status" text NOT NULL,
	"failure_reason" text
);
--> statement-breakpoint
CREATE TABLE "split_payments" (
	"id" text PRIMARY KEY NOT NULL,
	"reservation_number" text NOT NULL,
	"payment_number" integer NOT NULL,
	"total_payments" integer NOT NULL,
	"description" text NOT NULL,
	"amount_czk" numeric(14, 2) NOT NULL,
	"send_date" date NOT NULL,
	"guest_email" text,
	"guest_name" text,
	"guest_phone" text,
	"status" text NOT NULL,
	"stripe_session_id" text,
	"sent_at" timestamp with time zone,
	"failure_reason" text,
	"failure_count" integer,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stripe_payment_log" (
	"session_id" text PRIMARY KEY NOT NULL,
	"description" text NOT NULL,
	"amount_czk" numeric(14, 2) NOT NULL,
	"guest_email" text,
	"guest_phone" text,
	"guest_name" text,
	"reservation_number" text,
	"paid_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settlement_groups" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"transaction_ids" text[] NOT NULL,
	"invoice_ids" text[] NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"source" text,
	"period_start" date,
	"period_end" date,
	"gross_amount" numeric(14, 2),
	"commission_amount" numeric(14, 2),
	"net_amount" numeric(14, 2),
	"adjustments_amount" numeric(14, 2),
	"tax_withheld" numeric(14, 2),
	"report_file_id" text,
	"report_file_name" text,
	"report_url" text,
	"revenue_invoice_id" text
);
--> statement-breakpoint
CREATE TABLE "commission_settlements" (
	"id" text PRIMARY KEY NOT NULL,
	"unit_id" text NOT NULL,
	"room" text NOT NULL,
	"owner_name" text NOT NULL,
	"mode" text NOT NULL,
	"month" text NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"gbv" numeric(14, 2) NOT NULL,
	"ota_commission" numeric(14, 2) NOT NULL,
	"payment_fees" numeric(14, 2) NOT NULL,
	"net_sales" numeric(14, 2) NOT NULL,
	"cleaning" numeric(14, 2) NOT NULL,
	"laundry" numeric(14, 2) NOT NULL,
	"consumables" numeric(14, 2) NOT NULL,
	"subscriptions" numeric(14, 2) NOT NULL,
	"wear_tear" numeric(14, 2) NOT NULL,
	"misc" numeric(14, 2) NOT NULL,
	"operational_costs" numeric(14, 2) NOT NULL,
	"gross_profit" numeric(14, 2) NOT NULL,
	"commission_rate" numeric(6, 4) NOT NULL,
	"commission_amount" numeric(14, 2) NOT NULL,
	"payable_to_owner" numeric(14, 2) NOT NULL,
	"pool_rooms" text[],
	"pool_divisor" integer,
	"pool_gross_profit" numeric(14, 2),
	"reconciles" boolean NOT NULL,
	"reconcile_note" text,
	"status" text NOT NULL,
	"bank_transaction_id" text,
	"reconciled_at" timestamp with time zone,
	"emailed_at" timestamp with time zone,
	"emailed_to" text,
	"created_at" timestamp with time zone NOT NULL,
	"created_by" text NOT NULL
);
