ALTER TABLE "supplier_invoices" ALTER COLUMN "amount_czk" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "supplier_invoices" ALTER COLUMN "vat_amount_czk" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "revenue_invoices" ALTER COLUMN "amount_czk" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "additional_payments" ALTER COLUMN "amount_czk" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "additional_payments" ALTER COLUMN "stripe_fee_czk" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "payment_refunds" ALTER COLUMN "amount_czk" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "split_payments" ALTER COLUMN "amount_czk" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "stripe_payment_log" ALTER COLUMN "amount_czk" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "settlement_groups" ALTER COLUMN "gross_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "settlement_groups" ALTER COLUMN "commission_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "settlement_groups" ALTER COLUMN "net_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "settlement_groups" ALTER COLUMN "adjustments_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "settlement_groups" ALTER COLUMN "tax_withheld" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "gbv" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "ota_commission" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "payment_fees" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "net_sales" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "cleaning" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "laundry" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "consumables" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "subscriptions" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "wear_tear" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "misc" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "operational_costs" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "gross_profit" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "commission_rate" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "commission_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "payable_to_owner" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "commission_settlements" ALTER COLUMN "pool_gross_profit" SET DATA TYPE numeric;