/**
 * Country list + helpers for the "Nationality" selector on manual bookings.
 *
 * Ported from the rental-site's `src/lib/countries.ts` on purpose: the public
 * checkout already asks every guest for their country and sends Beds24 the
 * same `country` + `lang` pair, so operator-created phone bookings now carry
 * identical data. Keep the two files in sync when the mapping changes.
 *
 * Names and order are baked in rather than generated from `Intl.DisplayNames`
 * at render time: Node's ICU and the browser's disagree on a handful of names
 * (Hong Kong, Macao, Palestine) and on collation, which would be a hydration
 * mismatch the day this list is rendered on the server.
 *
 * Reading a nationality back off an existing booking (flag, adjective) lives in
 * `utils/nationalityUtils.ts` — this file is the input side only.
 */

export type CountryOption = { code: string; name: string };

/** ISO 3166-1 alpha-2 → English name, sorted by name. Single source of truth
 *  for the dropdown AND for server-side validation of the submitted value. */
export const COUNTRY_OPTIONS: readonly CountryOption[] = ([
  ['AF', "Afghanistan"],
  ['AL', "Albania"],
  ['DZ', "Algeria"],
  ['AD', "Andorra"],
  ['AO', "Angola"],
  ['AI', "Anguilla"],
  ['AG', "Antigua & Barbuda"],
  ['AR', "Argentina"],
  ['AM', "Armenia"],
  ['AW', "Aruba"],
  ['AU', "Australia"],
  ['AT', "Austria"],
  ['AZ', "Azerbaijan"],
  ['BS', "Bahamas"],
  ['BH', "Bahrain"],
  ['BD', "Bangladesh"],
  ['BB', "Barbados"],
  ['BY', "Belarus"],
  ['BE', "Belgium"],
  ['BZ', "Belize"],
  ['BJ', "Benin"],
  ['BM', "Bermuda"],
  ['BT', "Bhutan"],
  ['BO', "Bolivia"],
  ['BA', "Bosnia & Herzegovina"],
  ['BW', "Botswana"],
  ['BR', "Brazil"],
  ['VG', "British Virgin Islands"],
  ['BN', "Brunei"],
  ['BG', "Bulgaria"],
  ['BF', "Burkina Faso"],
  ['BI', "Burundi"],
  ['KH', "Cambodia"],
  ['CM', "Cameroon"],
  ['CA', "Canada"],
  ['CV', "Cape Verde"],
  ['KY', "Cayman Islands"],
  ['CF', "Central African Republic"],
  ['TD', "Chad"],
  ['CL', "Chile"],
  ['CN', "China"],
  ['CO', "Colombia"],
  ['KM', "Comoros"],
  ['CG', "Congo - Brazzaville"],
  ['CD', "Congo - Kinshasa"],
  ['CR', "Costa Rica"],
  ['CI', "Côte d’Ivoire"],
  ['HR', "Croatia"],
  ['CU', "Cuba"],
  ['CY', "Cyprus"],
  ['CZ', "Czechia"],
  ['DK', "Denmark"],
  ['DJ', "Djibouti"],
  ['DM', "Dominica"],
  ['DO', "Dominican Republic"],
  ['EC', "Ecuador"],
  ['EG', "Egypt"],
  ['SV', "El Salvador"],
  ['GQ', "Equatorial Guinea"],
  ['ER', "Eritrea"],
  ['EE', "Estonia"],
  ['SZ', "Eswatini"],
  ['ET', "Ethiopia"],
  ['FO', "Faroe Islands"],
  ['FJ', "Fiji"],
  ['FI', "Finland"],
  ['FR', "France"],
  ['GF', "French Guiana"],
  ['PF', "French Polynesia"],
  ['GA', "Gabon"],
  ['GM', "Gambia"],
  ['GE', "Georgia"],
  ['DE', "Germany"],
  ['GH', "Ghana"],
  ['GI', "Gibraltar"],
  ['GR', "Greece"],
  ['GL', "Greenland"],
  ['GD', "Grenada"],
  ['GP', "Guadeloupe"],
  ['GU', "Guam"],
  ['GT', "Guatemala"],
  ['GG', "Guernsey"],
  ['GN', "Guinea"],
  ['GW', "Guinea-Bissau"],
  ['GY', "Guyana"],
  ['HT', "Haiti"],
  ['HN', "Honduras"],
  ['HK', "Hong Kong"],
  ['HU', "Hungary"],
  ['IS', "Iceland"],
  ['IN', "India"],
  ['ID', "Indonesia"],
  ['IR', "Iran"],
  ['IQ', "Iraq"],
  ['IE', "Ireland"],
  ['IM', "Isle of Man"],
  ['IL', "Israel"],
  ['IT', "Italy"],
  ['JM', "Jamaica"],
  ['JP', "Japan"],
  ['JE', "Jersey"],
  ['JO', "Jordan"],
  ['KZ', "Kazakhstan"],
  ['KE', "Kenya"],
  ['KI', "Kiribati"],
  ['KW', "Kuwait"],
  ['KG', "Kyrgyzstan"],
  ['LA', "Laos"],
  ['LV', "Latvia"],
  ['LB', "Lebanon"],
  ['LS', "Lesotho"],
  ['LR', "Liberia"],
  ['LY', "Libya"],
  ['LI', "Liechtenstein"],
  ['LT', "Lithuania"],
  ['LU', "Luxembourg"],
  ['MO', "Macao"],
  ['MG', "Madagascar"],
  ['MW', "Malawi"],
  ['MY', "Malaysia"],
  ['MV', "Maldives"],
  ['ML', "Mali"],
  ['MT', "Malta"],
  ['MH', "Marshall Islands"],
  ['MQ', "Martinique"],
  ['MR', "Mauritania"],
  ['MU', "Mauritius"],
  ['MX', "Mexico"],
  ['FM', "Micronesia"],
  ['MD', "Moldova"],
  ['MC', "Monaco"],
  ['MN', "Mongolia"],
  ['ME', "Montenegro"],
  ['MA', "Morocco"],
  ['MZ', "Mozambique"],
  ['MM', "Myanmar (Burma)"],
  ['NA', "Namibia"],
  ['NR', "Nauru"],
  ['NP', "Nepal"],
  ['NL', "Netherlands"],
  ['NC', "New Caledonia"],
  ['NZ', "New Zealand"],
  ['NI', "Nicaragua"],
  ['NE', "Niger"],
  ['NG', "Nigeria"],
  ['KP', "North Korea"],
  ['MK', "North Macedonia"],
  ['NO', "Norway"],
  ['OM', "Oman"],
  ['PK', "Pakistan"],
  ['PW', "Palau"],
  ['PS', "Palestine"],
  ['PA', "Panama"],
  ['PG', "Papua New Guinea"],
  ['PY', "Paraguay"],
  ['PE', "Peru"],
  ['PH', "Philippines"],
  ['PL', "Poland"],
  ['PT', "Portugal"],
  ['PR', "Puerto Rico"],
  ['QA', "Qatar"],
  ['RE', "Réunion"],
  ['RO', "Romania"],
  ['RU', "Russia"],
  ['RW', "Rwanda"],
  ['WS', "Samoa"],
  ['SM', "San Marino"],
  ['ST', "São Tomé & Príncipe"],
  ['SA', "Saudi Arabia"],
  ['SN', "Senegal"],
  ['RS', "Serbia"],
  ['SC', "Seychelles"],
  ['SL', "Sierra Leone"],
  ['SG', "Singapore"],
  ['SK', "Slovakia"],
  ['SI', "Slovenia"],
  ['SB', "Solomon Islands"],
  ['SO', "Somalia"],
  ['ZA', "South Africa"],
  ['KR', "South Korea"],
  ['SS', "South Sudan"],
  ['ES', "Spain"],
  ['LK', "Sri Lanka"],
  ['KN', "St. Kitts & Nevis"],
  ['LC', "St. Lucia"],
  ['VC', "St. Vincent & Grenadines"],
  ['SD', "Sudan"],
  ['SR', "Suriname"],
  ['SE', "Sweden"],
  ['CH', "Switzerland"],
  ['SY', "Syria"],
  ['TW', "Taiwan"],
  ['TJ', "Tajikistan"],
  ['TZ', "Tanzania"],
  ['TH', "Thailand"],
  ['TL', "Timor-Leste"],
  ['TG', "Togo"],
  ['TO', "Tonga"],
  ['TT', "Trinidad & Tobago"],
  ['TN', "Tunisia"],
  ['TR', "Türkiye"],
  ['TM', "Turkmenistan"],
  ['TC', "Turks & Caicos Islands"],
  ['TV', "Tuvalu"],
  ['VI', "U.S. Virgin Islands"],
  ['UG', "Uganda"],
  ['UA', "Ukraine"],
  ['AE', "United Arab Emirates"],
  ['GB', "United Kingdom"],
  ['US', "United States"],
  ['UY', "Uruguay"],
  ['UZ', "Uzbekistan"],
  ['VU', "Vanuatu"],
  ['VA', "Vatican City"],
  ['VE', "Venezuela"],
  ['VN', "Vietnam"],
  ['YE', "Yemen"],
  ['ZM', "Zambia"],
  ['ZW', "Zimbabwe"],
] as const).map(([code, name]) => ({ code, name }));

const COUNTRY_CODE_SET = new Set(COUNTRY_OPTIONS.map((c) => c.code));

/** True if `code` is a known ISO 3166-1 alpha-2 code (case-insensitive). */
export function isValidCountryCode(code: string): boolean {
  return COUNTRY_CODE_SET.has(code.trim().toUpperCase());
}

/**
 * Country → ISO 639-1 language for the property's real source markets. Drives the
 * Beds24 booking `lang` so guest messaging localizes; unmapped countries → 'en'.
 * Beds24 itself falls back to English for any language with no template.
 */
const LANG_BY_COUNTRY: Record<string, string> = {
  CZ: 'cs',
  SK: 'sk',
  DE: 'de',
  AT: 'de',
  CH: 'de',
  LI: 'de',
  PL: 'pl',
  RU: 'ru',
  BY: 'ru',
  UA: 'uk',
  FR: 'fr',
  BE: 'fr',
  LU: 'fr',
  MC: 'fr',
  IT: 'it',
  SM: 'it',
  ES: 'es',
  MX: 'es',
  AR: 'es',
  NL: 'nl',
  PT: 'pt',
  BR: 'pt',
  HU: 'hu',
  RO: 'ro',
  MD: 'ro',
  BG: 'bg',
  GR: 'el',
  CY: 'el',
  HR: 'hr',
  SI: 'sl',
  RS: 'sr',
  DK: 'da',
  NO: 'no',
  SE: 'sv',
  FI: 'fi',
  TR: 'tr',
};

const LANG_NAMES: Record<string, string> = {
  bg: 'Bulgarian', cs: 'Czech', da: 'Danish', de: 'German', el: 'Greek',
  en: 'English', es: 'Spanish', fi: 'Finnish', fr: 'French', hr: 'Croatian',
  hu: 'Hungarian', it: 'Italian', nl: 'Dutch', no: 'Norwegian', pl: 'Polish',
  pt: 'Portuguese', ro: 'Romanian', ru: 'Russian', sk: 'Slovak', sl: 'Slovenian',
  sr: 'Serbian', sv: 'Swedish', tr: 'Turkish', uk: 'Ukrainian',
};

/** ISO 639-1 language code for a country (defaults to 'en'). */
export function countryToLang(code: string): string {
  return LANG_BY_COUNTRY[code.trim().toUpperCase()] ?? 'en';
}

/** English name of the language Beds24 will use for a country's messages. */
export function languageNameForCountry(code: string): string {
  const lang = countryToLang(code);
  return LANG_NAMES[lang] ?? lang;
}
